name: entrance_test
description: A new Flutter project.
publish_to: 'none'
version: 18.1.20+31

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  ansicolor: ^2.0.2
  cached_network_image: ^3.3.1
  country_code_picker: ^3.0.0
  dio: ^5.4.3+1
  dynamic_height_grid_view: ^0.0.4
  flutter:
    sdk: flutter

  flutter_downloader: ^1.11.7
  flutter_inappwebview: ^6.0.0
  flutter_native_splash: ^2.4.0
  get: ^4.6.6
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  readmore: ^3.0.0
  sqflite: ^2.3.3+1
  talker_dio_logger: ^4.2.0
  timeago: ^3.6.1
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/img_ves.png
  android_12:
    color: "#FFFFFF"
    image: assets/icons/ic_launcher.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
